steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
  # Build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  # Deploy
  - name: 'gcr.io/cloud-builders/npm'
    args: ['deploy']
    env: [
      'FIREBASE_TOKEN=${_FIREBASE_TOKEN}'
    ]